FROM ubuntu:18.04

USER root

ENV JAVA_MAJOR_VERSION=8
ENV LANG C.UTF-8

RUN                                          \
  apt-get update &&                          \
  apt-get install -y --no-install-recommends \
    unzip                                    \
    sudo                                     \
    git                                      \
    make                                     \
    cmake                                    \
    linux-tools-common                       \
    linux-tools-`uname -r`                   \
    build-essential                          \
    openjdk-8-jdk-headless                   \
    openjdk-8-dbg

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/

RUN git clone https://github.com/jvm-profiling-tools/perf-map-agent.git /usr/lib/jvm/perf-map-agent
WORKDIR /usr/lib/jvm/perf-map-agent
RUN \
  cmake . && \
  make

ARG MYUSER_UID=500

ENV DOCKER_BIN_DIR=/opt/docker/bin \
    MYUSER_BASE=/usr/local/myuser \
    MYUSER_USER_ID=${MYUSER_UID}

ENV MYUSER_HOME=${MYUSER_BASE}/ae \
    PATH=${DOCKER_BIN_DIR}:${PATH}

ENV MYUSER_LOGS_DIR=${MYUSER_HOME}/logs

RUN \
    ## Add myuser user and group ## \
    groupadd -g $MYUSER_USER_ID myuser && \
    useradd -m -g $MYUSER_USER_ID -u $MYUSER_USER_ID myuser && \
    ## Create the myuser directory structure ## \
    mkdir -p $MYUSER_LOGS_DIR && \
    chown -R myuser:myuser $MYUSER_BASE && \
    ## Create the docker bin dir ## \
    mkdir -p $DOCKER_BIN_DIR && \
    chown -R myuser:myuser $DOCKER_BIN_DIR

WORKDIR $MYUSER_HOME

USER myuser
